insert into REGION (id, name) values (1, 'Zaragoza');
insert into REGION (id, name) values (2, 'Belajen');
insert into REGION (id, name) values (3, 'Xiantang');
insert into REGION (id, name) values (4, 'Tanahbeureum');
insert into REGION (id, name) values (5, 'Ménaka');
insert into REGION (id, name) values (6, 'Drezdenko');
insert into REGION (id, name) values (7, 'Chapecó');
insert into REGION (id, name) values (8, 'Rabig');
insert into REGION (id, name) values (9, 'Caijiazha');
insert into REGION (id, name) values (10, 'Farkhor');
insert into REGION (id, name) values (11, 'Ouésso');
insert into REGION (id, name) values (12, 'Cumanayagua');
insert into REGION (id, name) values (13, 'Dafang');
insert into REGION (id, name) values (14, 'Helsingborg');
insert into REGION (id, name) values (15, 'Kholbon');
insert into REGION (id, name) values (16, 'Sosnovka');
insert into REGION (id, name) values (17, 'Alto de la Estancia');
insert into REGION (id, name) values (18, 'Ikalamavony');
insert into REGION (id, name) values (19, 'Busay');
insert into REGION (id, name) values (20, 'Ké-Macina');
insert into REGION (id, name) values (21, 'Viçosa');
insert into REGION (id, name) values (22, 'Mirkovci');
insert into REGION (id, name) values (23, 'Markova');
insert into REGION (id, name) values (24, 'Damu');
insert into REGION (id, name) values (25, 'Mönsterås');
insert into REGION (id, name) values (26, 'Pasar');
insert into REGION (id, name) values (27, 'Raszczyce');
insert into REGION (id, name) values (28, 'Xiancun');
insert into REGION (id, name) values (29, 'Caluquembe');
insert into REGION (id, name) values (30, 'Barra');
insert into REGION (id, name) values (31, 'Rizári');
insert into REGION (id, name) values (32, 'Sondo');
insert into REGION (id, name) values (33, 'Antas');
insert into REGION (id, name) values (34, 'Asunción');
insert into REGION (id, name) values (35, 'Bluefields');
insert into REGION (id, name) values (36, 'Munjul');
insert into REGION (id, name) values (37, 'Muramvya');
insert into REGION (id, name) values (38, 'Hexi');
insert into REGION (id, name) values (39, 'Maojiagang');
insert into REGION (id, name) values (40, 'Sucre');
insert into REGION (id, name) values (41, 'Newark');
insert into REGION (id, name) values (42, 'Riangwale');
insert into REGION (id, name) values (43, 'Yongjiahe');
insert into REGION (id, name) values (44, 'Jincheng');
insert into REGION (id, name) values (45, 'Digby');
insert into REGION (id, name) values (46, 'Giebułtów');
insert into REGION (id, name) values (47, 'Río Pico');
insert into REGION (id, name) values (48, 'Kathu');
insert into REGION (id, name) values (49, 'Alajuelita');
insert into REGION (id, name) values (50, 'Brudzew');
insert into REGION (id, name) values (51, 'Krzyżanowice');
insert into REGION (id, name) values (52, 'Nzega');
insert into REGION (id, name) values (53, 'Puntaru');
insert into REGION (id, name) values (54, 'Trabulheira');
insert into REGION (id, name) values (55, 'Nixi');
insert into REGION (id, name) values (56, 'Owase');
insert into REGION (id, name) values (57, 'Vágia');
insert into REGION (id, name) values (58, 'Wukari');
insert into REGION (id, name) values (59, 'Zouérat');
insert into REGION (id, name) values (60, 'Gävle');
insert into REGION (id, name) values (61, 'Santa Fe');
insert into REGION (id, name) values (62, 'Manjing');
insert into REGION (id, name) values (63, 'Mirosławiec');
insert into REGION (id, name) values (64, 'Walichnowy');
insert into REGION (id, name) values (65, 'Dalu');
insert into REGION (id, name) values (66, 'Besuki Dua');
insert into REGION (id, name) values (67, 'Wangren');
insert into REGION (id, name) values (68, 'Bonneville');
insert into REGION (id, name) values (69, 'Billdal');
insert into REGION (id, name) values (70, 'Pinhal General');
insert into REGION (id, name) values (71, 'Kanugrahan');
insert into REGION (id, name) values (72, 'Brandýs nad Labem-Stará Boleslav');
insert into REGION (id, name) values (73, 'Cláudio');
insert into REGION (id, name) values (74, 'Salamnunggal');
insert into REGION (id, name) values (75, 'Sang-e Chārak');
insert into REGION (id, name) values (76, 'Łącko');
insert into REGION (id, name) values (77, 'Konibodom');
insert into REGION (id, name) values (78, 'København');
insert into REGION (id, name) values (79, 'Wuning');
insert into REGION (id, name) values (80, 'Emiliano Zapata');
insert into REGION (id, name) values (81, 'Hồ Xá');
insert into REGION (id, name) values (82, 'San Jose Village');
insert into REGION (id, name) values (83, 'Mizur');
insert into REGION (id, name) values (84, 'Falun');
insert into REGION (id, name) values (85, 'Mubi');
insert into REGION (id, name) values (86, 'São Silvestre');
insert into REGION (id, name) values (87, 'Calanogas');
insert into REGION (id, name) values (88, 'Anyar');
insert into REGION (id, name) values (89, 'Salamnunggal');
insert into REGION (id, name) values (90, 'Dvurechensk');
insert into REGION (id, name) values (91, 'Horred');
insert into REGION (id, name) values (92, 'Monasterevin');
insert into REGION (id, name) values (93, 'Kumo');
insert into REGION (id, name) values (94, 'Bačka Palanka');
insert into REGION (id, name) values (95, 'Huadi');
insert into REGION (id, name) values (96, 'Qingshi');
insert into REGION (id, name) values (97, 'Villa Serrano');
insert into REGION (id, name) values (98, 'Tønsberg');
insert into REGION (id, name) values (99, 'Novhorod-Sivers’kyy');
insert into REGION (id, name) values (100, 'Yanggu');
insert into REGION (id, name) values (101, 'Kuaro');
insert into REGION (id, name) values (102, 'Abadou');
insert into REGION (id, name) values (103, 'Ash Shiḩr');
insert into REGION (id, name) values (104, 'Dajin');
insert into REGION (id, name) values (105, 'Não Me Toque');
insert into REGION (id, name) values (106, 'Yangsha');
insert into REGION (id, name) values (107, 'Siqian');
insert into REGION (id, name) values (108, 'Verkhnyaya Belka');
insert into REGION (id, name) values (109, 'Lam Sonthi');
insert into REGION (id, name) values (110, 'Salekhard');
insert into REGION (id, name) values (111, 'Luanshya');
insert into REGION (id, name) values (112, 'Cumanayagua');
insert into REGION (id, name) values (113, 'Namboongan');
insert into REGION (id, name) values (114, 'Karukh');
insert into REGION (id, name) values (115, 'Kidal');
insert into REGION (id, name) values (116, 'Amboise');
insert into REGION (id, name) values (117, 'Posse');
insert into REGION (id, name) values (118, 'La Peña');
insert into REGION (id, name) values (119, 'Dazhou');
insert into REGION (id, name) values (120, 'pamas');
insert into REGION (id, name) values (121, 'Zengjia');
insert into REGION (id, name) values (122, 'Qobu');
insert into REGION (id, name) values (123, 'Santo Domingo');
insert into REGION (id, name) values (124, 'Foshan');
insert into REGION (id, name) values (125, 'Tiadiaye');
insert into REGION (id, name) values (126, 'Harjavalta');
insert into REGION (id, name) values (127, 'Lasusua');
insert into REGION (id, name) values (128, 'Longcun');
insert into REGION (id, name) values (129, 'Yafran');
insert into REGION (id, name) values (130, 'Il’inskiy Pogost');
insert into REGION (id, name) values (131, 'Milanówek');
insert into REGION (id, name) values (132, 'Khūgyāṉī');
insert into REGION (id, name) values (133, 'Berbek');
insert into REGION (id, name) values (134, 'Camindangan');
insert into REGION (id, name) values (135, 'Uścimów Stary');
insert into REGION (id, name) values (136, 'As Salţ');
insert into REGION (id, name) values (137, 'Whitchurch');
insert into REGION (id, name) values (138, 'Ryazhsk');
insert into REGION (id, name) values (139, 'Räpina');
insert into REGION (id, name) values (140, 'Tazemmourt');
insert into REGION (id, name) values (141, 'Huatai');
insert into REGION (id, name) values (142, 'Kohtla-Järve');
insert into REGION (id, name) values (143, 'Mombaça');
insert into REGION (id, name) values (144, 'Yūki');
insert into REGION (id, name) values (145, 'Mahābād');
insert into REGION (id, name) values (146, 'Omuthiya');
insert into REGION (id, name) values (147, 'Ar Ramthā');
insert into REGION (id, name) values (148, 'Resende');
insert into REGION (id, name) values (149, 'Oklahoma City');
insert into REGION (id, name) values (150, 'Aix-en-Provence');
insert into REGION (id, name) values (151, 'Fort Wayne');
insert into REGION (id, name) values (152, 'Wielichowo');
insert into REGION (id, name) values (153, 'Zhonghuopu');
insert into REGION (id, name) values (154, 'Dongshangguan');
insert into REGION (id, name) values (155, 'Weishan');
insert into REGION (id, name) values (156, 'Medvezh’yegorsk');
insert into REGION (id, name) values (157, 'Sibanicú');
insert into REGION (id, name) values (158, 'Xiheshan');
insert into REGION (id, name) values (159, 'San Juan');
insert into REGION (id, name) values (160, 'Bitung');
insert into REGION (id, name) values (161, 'Motala');
insert into REGION (id, name) values (162, 'Mboursou Léré');
insert into REGION (id, name) values (163, 'Roermond');
insert into REGION (id, name) values (164, 'Aurillac');
insert into REGION (id, name) values (165, 'Pereyaslav-Khmel’nyts’kyy');
insert into REGION (id, name) values (166, 'Worcester');
insert into REGION (id, name) values (167, 'Bagaces');
insert into REGION (id, name) values (168, 'Jiuzihe');
insert into REGION (id, name) values (169, 'Sibagat');
insert into REGION (id, name) values (170, 'Cergy-Pontoise');
insert into REGION (id, name) values (171, 'Wujia');
insert into REGION (id, name) values (172, 'Vila Moreira');
insert into REGION (id, name) values (173, 'Xiadian');
insert into REGION (id, name) values (174, 'Sergelen');
insert into REGION (id, name) values (175, 'Laolong');
insert into REGION (id, name) values (176, 'Bendorubuh');
insert into REGION (id, name) values (177, 'Danao');
insert into REGION (id, name) values (178, 'Bontoc');
insert into REGION (id, name) values (179, 'Denpasar');
insert into REGION (id, name) values (180, 'Yidu');
insert into REGION (id, name) values (181, 'Beigao');
insert into REGION (id, name) values (182, 'Lubień Kujawski');
insert into REGION (id, name) values (183, 'Zaragoza');
insert into REGION (id, name) values (184, 'Wichita');
insert into REGION (id, name) values (185, 'Jinrui');
insert into REGION (id, name) values (186, 'Tsaghkunk’');
insert into REGION (id, name) values (187, 'Qiqian');
insert into REGION (id, name) values (188, 'Albania');
insert into REGION (id, name) values (189, 'Erping');
insert into REGION (id, name) values (190, 'Přimda');
insert into REGION (id, name) values (191, 'Sovetsk');
insert into REGION (id, name) values (192, 'Guisguis');
insert into REGION (id, name) values (193, 'Halimaung Jaya (F-3)');
insert into REGION (id, name) values (194, 'Boyany');
insert into REGION (id, name) values (195, 'Balzan');
insert into REGION (id, name) values (196, 'Traiguén');
insert into REGION (id, name) values (197, 'Lovrenc na Pohorju');
insert into REGION (id, name) values (198, 'Renhe');
insert into REGION (id, name) values (199, 'Novi Bilokorovychi');
insert into REGION (id, name) values (200, 'Uherský Brod');
insert into REGION (id, name) values (201, 'Lysekil');
insert into REGION (id, name) values (202, 'Shuidong');
insert into REGION (id, name) values (203, 'Berlin');
insert into REGION (id, name) values (204, 'Nogliki');
insert into REGION (id, name) values (205, 'Poço Verde');
insert into REGION (id, name) values (206, 'Kamirenjaku');
insert into REGION (id, name) values (207, 'Kačanik');
insert into REGION (id, name) values (208, 'Järfälla');
insert into REGION (id, name) values (209, 'Casal da Anja');
insert into REGION (id, name) values (210, 'Zhanghua');
insert into REGION (id, name) values (211, 'Medicine Hat');
insert into REGION (id, name) values (212, 'Madrid');
insert into REGION (id, name) values (213, 'Pedra Azul');
insert into REGION (id, name) values (214, 'Jianggao');
insert into REGION (id, name) values (215, 'Balazar');
insert into REGION (id, name) values (216, 'Thị Trấn Thanh Lưu');
insert into REGION (id, name) values (217, 'Balud');
insert into REGION (id, name) values (218, 'Ibarreta');
insert into REGION (id, name) values (219, 'Gambarjati');
insert into REGION (id, name) values (220, 'Cuamba');
insert into REGION (id, name) values (221, 'Bykov');
insert into REGION (id, name) values (222, 'Puerto Quijarro');
insert into REGION (id, name) values (223, 'Kherson');
insert into REGION (id, name) values (224, 'Chiantla');
insert into REGION (id, name) values (225, 'Chamouny');
insert into REGION (id, name) values (226, 'Kangar');
insert into REGION (id, name) values (227, 'Hữu Lũng');
insert into REGION (id, name) values (228, 'Sukamaju');
insert into REGION (id, name) values (229, 'Staryy Oskol');
insert into REGION (id, name) values (230, 'Tournai');
insert into REGION (id, name) values (231, 'Quimistán');
insert into REGION (id, name) values (232, 'Cerkvenjak');
insert into REGION (id, name) values (233, 'Roubaix');
insert into REGION (id, name) values (234, 'Parapat');
insert into REGION (id, name) values (235, 'Minle');
insert into REGION (id, name) values (236, 'Jaga');
insert into REGION (id, name) values (237, 'Povedniki');
insert into REGION (id, name) values (238, 'Kidal');
insert into REGION (id, name) values (239, 'Sandefjord');
insert into REGION (id, name) values (240, 'Banga');
insert into REGION (id, name) values (241, 'San Justo');
insert into REGION (id, name) values (242, 'Jampang Kulon');
insert into REGION (id, name) values (243, 'Örebro');
insert into REGION (id, name) values (244, 'Zhongguan');
insert into REGION (id, name) values (245, 'Sanjiao');
insert into REGION (id, name) values (246, 'Ilihan');
insert into REGION (id, name) values (247, 'Xincheng');
insert into REGION (id, name) values (248, 'Xiuyu');
insert into REGION (id, name) values (249, 'Tagkawayan Sabang');
insert into REGION (id, name) values (250, 'Sigaboy');
insert into REGION (id, name) values (251, 'Kasli');
insert into REGION (id, name) values (252, 'Blang Dalam');
insert into REGION (id, name) values (253, 'Chão');
insert into REGION (id, name) values (254, 'Stockholm');
insert into REGION (id, name) values (255, 'Osogbo');
insert into REGION (id, name) values (256, 'Rawson');
insert into REGION (id, name) values (257, 'Huangjing');
insert into REGION (id, name) values (258, 'Jangkat');
insert into REGION (id, name) values (259, 'Chenhu');
insert into REGION (id, name) values (260, 'Bonabéri');
insert into REGION (id, name) values (261, 'Ambelókipoi');
insert into REGION (id, name) values (262, 'Manquiring');
insert into REGION (id, name) values (263, 'Rączna');
insert into REGION (id, name) values (264, 'Pesagen');
insert into REGION (id, name) values (265, 'Manouba');
insert into REGION (id, name) values (266, 'Bebae');
insert into REGION (id, name) values (267, 'Espinal');
insert into REGION (id, name) values (268, 'Chodzież');
insert into REGION (id, name) values (269, 'Quelimane');
insert into REGION (id, name) values (270, 'Nezhinka');
insert into REGION (id, name) values (271, 'Fuli');
insert into REGION (id, name) values (272, 'Camp Ithier');
insert into REGION (id, name) values (273, 'Pidigan');
insert into REGION (id, name) values (274, 'Shu');
insert into REGION (id, name) values (275, 'Bamencheng');
insert into REGION (id, name) values (276, 'Dolores');
insert into REGION (id, name) values (277, 'Hamburg');
insert into REGION (id, name) values (278, 'Iaçu');
insert into REGION (id, name) values (279, 'Kalahang');
insert into REGION (id, name) values (280, 'Sukojember');
insert into REGION (id, name) values (281, 'Gaotuo');
insert into REGION (id, name) values (282, 'Pak Chom');
insert into REGION (id, name) values (283, 'Zelenogradsk');
insert into REGION (id, name) values (284, 'Shihuang');
insert into REGION (id, name) values (285, 'Cannes');
insert into REGION (id, name) values (286, 'Wantou');
insert into REGION (id, name) values (287, 'Fahraj');
insert into REGION (id, name) values (288, 'Cotton Ground');
insert into REGION (id, name) values (289, 'Dorp Antriol');
insert into REGION (id, name) values (290, 'Pulosari');
insert into REGION (id, name) values (291, 'Tobi Village');
insert into REGION (id, name) values (292, 'Dadapan');
insert into REGION (id, name) values (293, 'Daoqiao');
insert into REGION (id, name) values (294, 'Weligama');
insert into REGION (id, name) values (295, 'Stockholm');
insert into REGION (id, name) values (296, 'Mozi');
insert into REGION (id, name) values (297, 'Thị Trấn Yên Ninh');
insert into REGION (id, name) values (298, 'Yvetot');
insert into REGION (id, name) values (299, 'Lianglin');
insert into REGION (id, name) values (300, 'Wawa');
